Repository zoobc/zoobc-core, pull requests merged in 2021-02, with the labels that each got.

#1445 fix logic used to validate spine blocks
  core/smith/strategy/blocksmithStrategySpine.go
  main.go
Labels: BUG, do not merge

#1452 Restored spine blocks creation time validation
  core/smith/strategy/blocksmithStrategySpine.go
Labels: BUG

#1451 Update some go module to latest stable versions
  go.mod
  go.sum
Labels: ENHANCE

#1453 Update go modules
  go.mod
  go.sum
Labels: BUG

#1437 Update max message length and MinRollbackBlocks
  common/constant/blockchainSync.go
  common/constant/snapshot.go
  common/constant/transaction.go
  common/query/pendingTransactionQuery_test.go
  common/storage/scrambleNodeStorage_test.go
  common/transaction/transactionGeneral.go
  core/service/blockSpineService_test.go
  core/service/nodeAddressInfoService.go
  core/service/nodeRegistrationCoreService_test.go
  core/service/receiptService_test.go
  core/service/snapshotBasicChunkStrategy_test.go
  core/service/snapshotMainBlockService_test.go
  go.sum
  main.go
Labels: CORE

#1447 update genesis participation score to the max score
  common/constant/participationScore.go
Labels: REQUIRE_RESET

#1448 change initial score for node admittance to 20% of max score
  common/constant/participationScore.go
Labels: CORE

#1455 fix the logic to choose new reference block
  core/service/blockSpineService.go
Labels: BUG

#1457 Fix check for high cpu usage in anti-spam filter for post transaction api
  api/service/transactionApiService.go
Labels: BUG

#1458 Allow a node to download even just one block from its peers
  common/constant/blockchainSync.go
Labels: BUG

#1459 1456 ethereum account address
  cmd/account/account.go
  common/accounttype/accountTypeUtil.go
  common/accounttype/accountTypeUtil_test.go
  common/accounttype/ethAccountType.go
  common/accounttype/ethAccountType_test.go
  common/constant/signature.go
  common/model/accountType.pb.go
  common/model/signature.pb.go
  go.mod
  go.sum
Labels: FEATURE

#1461 allow send money transaction to have 0 amount
  common/transaction/sendMoney.go
Labels: ENHANCE

#1467 Disable updating node public key in Update Node Registration Transaction
  common/transaction/nodeRegistrationUpdate.go
Labels: BUG

#1466 Change spine block smithing behavior
  cmd/block/blockGenerator.go
  core/service/blockSpineService.go
  core/smith/strategy/blocksmithStrategyMain.go
  core/smith/strategy/blocksmithStrategyMain_test.go
  core/smith/strategy/blocksmithStrategySpine.go
  core/smith/strategy/util.go
  main.go
Labels: CORE

#1465 adding function getLiquidTransaction
  api/api.go
  api/client/GetLiquidTransactions/client.go
  api/handler/liquidTransactionHandler.go
  api/service/liquidTransactionApiService.go
  api/service/liquidTransactionApiService_test.go
  cmd/transaction/generator.go
  common/database/migration.go
  common/model/liquidPayment.pb.go
  common/service/liquidPayment.pb.go
  common/service/liquidPayment.pb.gw.go
Labels: API

#1468 change phrase 'sendMoney' to 'sendZBC'
  api/service/transactionApiService_test.go
  cmd/transaction/cmd.go
  cmd/transaction/const.go
  cmd/transaction/generator.go
  common/fee/constant.go
  common/fee/feeScaleService.go
  common/fee/feeScaleService_test.go
  common/model/event.pb.go
  common/model/transaction.pb.go
  common/model/transactionBody.go
  common/service/transaction.pb.go
  common/service/transaction.pb.gw.go
  common/transaction/approvalEscrowTransaction.go
  common/transaction/feeVoteCommit_test.go
  common/transaction/nodeRegistration.go
  common/transaction/nodeRegistrationClaim_test.go
  common/transaction/nodeRegistrationUpdate_test.go
  common/transaction/nodeRegistration_test.go
  common/transaction/removeNodeRegistration_test.go
  common/transaction/sendMoney.go
  common/transaction/sendMoney_test.go
  common/transaction/transaction.go
  common/transaction/transactionGeneral_test.go
  common/transaction/transaction_test.go
  core/service/blockMainService.go
  core/service/blockMainService_test.go
  core/service/blockSpineService_test.go
  core/service/genesisCoreService.go
  core/service/transactionCoreService_test.go
Labels: ENHANCE

#1469 Change account address required in config file to an encoded address
  api/client/GenerateNodeKey/client.go
  api/client/GetAccountBalance/client.go
  api/client/GetAccountBalances/client.go
  api/client/GetAccountDataset/main.go
  api/client/GetAccountDatasets/main.go
  api/client/GetAccountLedgers/main.go
  api/client/GetBlockByHeight/client.go
  api/client/GetBlockByID/client.go
  api/client/GetBlocks/client.go
  api/client/GetEscrowTransaction/main.go
  api/client/GetEscrowTransactions/main.go
  api/client/GetHostInfo/client.go
  api/client/GetHostPeers/client.go
  api/client/GetLatestParticipationScoreByNodeID/client.go
  api/client/GetLiquidTransactions/client.go
  api/client/GetMempoolTransaction/main.go
  api/client/GetMempoolTransactions/main.go
  api/client/GetMultisigAddressesByBlockHeightRange/client.go
  api/client/GetMultisigInfo/client.go
  api/client/GetNodeAddressInfo/client.go
  api/client/GetNodeHardware/client.go
  api/client/GetNodeRegistration/client.go
  api/client/GetNodeRegistrations/client.go
  api/client/GetNodeRegistrationsByNodePublicKeys/client.go
  api/client/GetNodeTime/client.go
  api/client/GetParticipantsByMultisigAddresses/client.go
  api/client/GetParticipationScores/client.go
  api/client/GetPendingNodeRegistrations/client.go
  api/client/GetPendingTransactionDetailByTransactionHash/client.go
  api/client/GetPendingTransactions/client.go
  api/client/GetPendingTransactionsByHeight/client.go
  api/client/GetProofOfOwnership/client.go
  api/client/GetPublishedReceipts/client.go
  api/client/GetSkippedBlockSmiths/client.go
  api/client/GetTransaction/client.go
  api/client/GetTransactionMinimumFee/client.go
  api/client/GetTransactions/client.go
  api/client/GetTransactionsByBlockHeight/client.go
  api/client/HealthCheck/client.go
  api/client/PostTransaction/client.go
  cmd/configure/cmd.go
  common/model/config.go
  common/util/loadConfig.go
  common/util/loadConfig_test.go
  config.toml
  config2.toml
  config3.toml
  config4.toml
  config5.toml
  main.go
Labels: ENHANCE

#1470 Update genesis generate command to use encoded address in configuration instead of hex
  cmd/genesisblock/cmd.go
  resource/templates/alpha.genesisAccountAddresses.json
Labels: ENHANCE

#1471 Let genesis generate command add the constant instead of a number as default node participation score
  cmd/genesisblock/cmd.go
Labels: BUG

#1472 Update well known peers that configure command uses to feed config.toml: only use domain names, since IP addresses can change in beta
  cmd/configure/const.go
Labels: BUG

#1464 Fix Node Receipts not generated when Sending/Receiving blocks
  cmd/block/blockGenerator.go
  common/constant/p2p.go
  common/constant/participationScore.go
  common/constant/receipt.go
  common/util/ParticipationScore.go
  common/util/block.go
  core/service/blockMainService.go
  core/service/blockMainService_test.go
  core/service/nodeRegistrationCoreService.go
  core/service/receiptService.go
  core/service/receiptService_test.go
  core/util/receiptUtil.go
  main.go
  observer/observer.go
  p2p/client/peerServiceClient.go
  p2p/p2p.go
  p2p/service/p2pServerService.go
  p2p/service/p2pServerService_test.go
Labels: BUG

#1477 fix escrow mapping
  common/util/escrow.go
  common/util/escrow_test.go
Labels: CORE

#1476 change implementation of batch receipt generation
  common/constant/receipt.go
  common/storage/blockState.go
  common/storage/blocksStorage.go
  common/storage/mempoolBackupStorage.go
  common/storage/mempoolStorage.go
  common/storage/nodeAddressInfoStorage.go
  common/storage/nodeAdmissionTimestampStorage.go
  common/storage/nodeRegistration.go
  common/storage/nodeShardCacheStorage.go
  common/storage/receiptPoolCacheStorage.go
  common/storage/receiptPoolCacheStorage_test.go
  common/storage/receiptReminder.go
  common/storage/scrambleNodeStorage.go
  common/storage/storage.go
  core/blockchainsync/blockchainSync.go
  core/service/blockSpineService.go
  core/service/receiptService.go
  core/service/receiptService_test.go
  main.go
Labels: CORE

#1478 fix instances passed to operations
  common/transaction/transaction.go
Labels: CORE
