Repository zoobc/zoobc-core, pull requests merged in 2021-01, with the labels that each got.

#1422 Possible fix for pushblock deadlock
  core/service/blockMainService.go
  core/service/blockSpineService.go
Labels: BUG

#1425 Make sure db tx complete in push block
  common/blocker/blocker.go
  core/service/blockMainService.go
  core/service/blockSpineService.go
Labels: CORE

#1427 sqlite with WAL
  .gitignore
  common/constant/sqlConnetion.go
  common/constant/transaction.go
  common/database/sqlite.go
  common/util/loadConfig.go
  core/service/blockMainService.go
Labels: ENHANCE

#1429 disable blocks storage temporarily for debug
  common/util/block.go
Labels: BUG

#1431 GetLastBlock from db and not from cache
  core/service/blockMainService.go
  core/service/blockMainService_test.go
  core/service/blockSpineService.go
  core/service/blockSpineService_test.go
Labels: ENHANCE

#1433 Fix prioritylock counter
  common/queue/priorityLock.go
Labels: BUG

#1423 fix require-escrow dataset attribute behavior
  common/transaction/transactionGeneral.go
  common/transaction/transactionGeneral_test.go
  common/util/checkHelper.go
Labels: BUG, CORE

#1438 Make sure the block don't have transactions if the skipped blocksmith is more than 10
  common/constant/smith.go
Labels: CORE

#1441 add param for getting transaction by Block Height
  api/client/GetTransactionsByBlockHeight/client.go
  api/service/transactionApiService.go
  api/service/transactionApiService_test.go
  common/model/transaction.pb.go
Labels: API

#1443 fixing transaction not filtered
  api/service/transactionApiService.go
Labels: BUG

#1449 Fix registering node with same pub key of a deleted node:
  common/queue/priorityLock_test.go
  common/transaction/nodeRegistration.go
Labels: BUG
